<a href="https://colab.research.google.com/github/Coder-twhjr/MindReaderGame-Claude-Shannon-s-Algorithm/blob/main/Mind_Reading_Machine_Based_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mind Reading Machine Based Algorithm




---

#### Last Two Players Inputs

In [1]:
last_1 = 0
last_2 = 0



---

#### The `inputs` Array

In [2]:
import numpy as np

inputs = np.zeros(shape=(2, 2, 2), dtype=int)
inputs

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

---

#### The `update_inputs()` Function

In [3]:
def update_inputs(current):
  if inputs[last_2][last_1][0] == current:
    inputs[last_2][last_1][1] = 1 
    inputs[last_2][last_1][0] = current
  else:
    inputs[last_2][last_1][1] = 0 
    inputs[last_2][last_1][0] = current
 
  last_2 = last_1 
  last_1 = current 

---

#### The `prediction()` Function

In [4]:
def prediction():
  if inputs[last_2][last_1][1] == 1: 
    predict = inputs[last_2][last_1][0]    
  else:
    predict = random.randint(0, 1)  
  return predict

---

####The `update_scores()` Function

In [6]:
scores = [0, 0]

def update_scores(predicted, player_input):
  if predicted == player_input:
    scores[0] =  scores[0] + 1
    print("\nComputer Score:", scores[0], "\nPlayer Score:", scores[1]) 
               
  else:
    scores[1] = scores[1] + 1
    print("\nComputer Score:", scores[0], "\nPlayer Score:", scores[1])

---

####The `reset()` Function

In [7]:
def reset():
  for i in range(2):
    for j in range(2):
      for k in range(2):
        inputs[i][j][k] = 0

  for i in range(len(scores)):
    scores[i] = 0      

---

####Putting Everything Together

In [8]:
import random
import numpy as np

inputs = np.zeros(shape=(2, 2, 2), dtype=int) 

last_1 = 0
last_2 = 0

scores = [0, 0] 

def update_inputs(current):
  global last_1, last_2
  if inputs[last_2][last_1][0] == current:
    inputs[last_2][last_1][1] = 1 
    inputs[last_2][last_1][0] = current
  else:
    inputs[last_2][last_1][1] = 0 
    inputs[last_2][last_1][0] = current
  
  last_2 = last_1 
  last_1 = current 
    
def prediction():
  if inputs[last_2][last_1][1] == 1: 
    predict = inputs[last_2][last_1][0]    
  else:
    predict = random.randint(0, 1)  
  return predict

def update_scores(predicted, player_input):  
  if predicted == player_input:
    scores[0] = scores[0] + 1
    print("\nComputer Score:", scores[0], "\nPlayer Score:", scores[1]) 
        
  else:
    scores[1] = scores[1] + 1
    print("\nComputer Score:", scores[0], "\nPlayer Score:", scores[1]) 

def reset():
  for i in range(2):
    for j in range(2):
      for k in range(2):
        inputs[i][j][k] = 0
  
  for i in range(2):
    scores[i] = 0

---

####The `gameplay()` Function

In [9]:
def gameplay():
  reset()
  print(inputs)
  print(scores)
  valid_entries = ['0', '1']
  while True:
    predicted = prediction()
    player_input = input("\nEnter either 1 or 0: ")
    
    while player_input not in valid_entries:
      print("\nInvalid Input!")
      player_input = input("Please enter either 1 or 0: ")
    
    player_input = int(player_input)
    update_inputs(player_input)
    update_scores(predicted, player_input)
        
    if scores[0] == 20:
      print("\nBad Luck, Computer Wins!\n")
      break
        
    elif scores[1] == 20:
      print("\nCongrats, You Won!\n")
      break

In [10]:
gameplay()

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[0, 0]

Enter either 1 or 0: 1

Computer Score: 1 
Player Score: 0

Enter either 1 or 0: 1

Computer Score: 1 
Player Score: 1

Enter either 1 or 0: 1

Computer Score: 2 
Player Score: 1

Enter either 1 or 0: 

Invalid Input!
Please enter either 1 or 0: 0

Computer Score: 2 
Player Score: 2

Enter either 1 or 0: 0

Computer Score: 3 
Player Score: 2

Enter either 1 or 0: 1

Computer Score: 3 
Player Score: 3

Enter either 1 or 0: 0

Computer Score: 3 
Player Score: 4

Enter either 1 or 0: 1

Computer Score: 3 
Player Score: 5

Enter either 1 or 0: 0

Computer Score: 4 
Player Score: 5

Enter either 1 or 0: 0

Computer Score: 5 
Player Score: 5

Enter either 1 or 0: 0

Computer Score: 5 
Player Score: 6

Enter either 1 or 0: 1

Computer Score: 6 
Player Score: 6

Enter either 1 or 0: 1

Enter either 1 or 0: 0

Computer Score: 6 
Player Score: 7

Computer Score: 6 
Player Score: 8

Enter either 1 or 0: 0

Computer Score: 6 
Player Score: 9

Enter eithe

---